version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "9090:80"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build: ./backend
    ports:
      - "9091:8000"
    volumes:
      - ./backend:/app
      - vaxninja-data:/data
    environment:
      - DB_PATH=/data/vaxninja.db
    restart: unless-stopped

volumes:
  vaxninja-data:
